import type { Activity } from "@/types/activity";
import type { Deal } from "@/types/deal";
import type { Lead } from "@/types/lead";
import type { Workspace } from "@/types/workspace";

export const mockWorkspaces: Workspace[] = [
  { id: "ws_acme", name: "Acme Vendas", plan: "pro" },
  { id: "ws_nova", name: "Agência Nova", plan: "free" },
];

export const mockCurrentUser = {
  name: "Ana Souza",
  email: "ana@acmevendas.com",
  role: "admin" as const,
};

export const mockOwners = ["Ana Souza", "Carlos Mendes", "Bruna Ferreira"];

export const mockLeads: Lead[] = [
  {
    id: "lead_01",
    name: "Mariana Costa",
    email: "mariana.costa@grupovialog.com.br",
    phone: "(11) 98765-4321",
    company: "Grupo Vialog",
    jobTitle: "Gerente de Compras",
    status: "qualificado",
    ownerName: "Ana Souza",
    createdAt: "2026-06-02",
  },
  {
    id: "lead_02",
    name: "Rafael Almeida",
    email: "rafael@almeidaadvocacia.com.br",
    phone: "(21) 99887-1234",
    company: "Almeida Advocacia",
    jobTitle: "Sócio",
    status: "novo",
    ownerName: "Carlos Mendes",
    createdAt: "2026-07-28",
  },
  {
    id: "lead_03",
    name: "Juliana Pereira",
    email: "juliana.pereira@nordestetech.com",
    phone: "(81) 98123-4567",
    company: "Nordeste Tech",
    jobTitle: "CTO",
    status: "contatado",
    ownerName: "Bruna Ferreira",
    createdAt: "2026-07-18",
  },
  {
    id: "lead_04",
    name: "Eduardo Santos",
    email: "eduardo@santosimoveis.com.br",
    phone: "(31) 99456-7890",
    company: "Santos Imóveis",
    jobTitle: "Diretor Comercial",
    status: "desqualificado",
    ownerName: "Ana Souza",
    createdAt: "2026-05-20",
  },
  {
    id: "lead_05",
    name: "Camila Rodrigues",
    email: "camila.rodrigues@bellamoda.com.br",
    phone: "(11) 97654-3210",
    company: "Bella Moda",
    jobTitle: "Fundadora",
    status: "qualificado",
    ownerName: "Carlos Mendes",
    createdAt: "2026-06-25",
  },
  {
    id: "lead_06",
    name: "Thiago Oliveira",
    email: "thiago@oliveiralog.com",
    phone: "(41) 98234-5678",
    company: "Oliveira Logística",
    jobTitle: "Gerente de TI",
    status: "novo",
    ownerName: "Bruna Ferreira",
    createdAt: "2026-07-29",
  },
  {
    id: "lead_07",
    name: "Fernanda Lima",
    email: "fernanda.lima@clinicavitta.com.br",
    phone: "(19) 99345-6789",
    company: "Clínica Vitta",
    jobTitle: "Administradora",
    status: "contatado",
    ownerName: "Ana Souza",
    createdAt: "2026-07-10",
  },
  {
    id: "lead_08",
    name: "Bruno Carvalho",
    email: "bruno@carvalhoconsult.com.br",
    phone: "(48) 98456-7891",
    company: "Carvalho Consultoria",
    jobTitle: "Consultor Sênior",
    status: "novo",
    ownerName: "Carlos Mendes",
    createdAt: "2026-07-27",
  },
  {
    id: "lead_09",
    name: "Patrícia Gomes",
    email: "patricia.gomes@ecosolar.com.br",
    phone: "(85) 99567-8912",
    company: "EcoSolar Energia",
    jobTitle: "Gerente de Vendas",
    status: "qualificado",
    ownerName: "Bruna Ferreira",
    createdAt: "2026-06-18",
  },
  {
    id: "lead_10",
    name: "Lucas Martins",
    email: "lucas.martins@martinsagro.com.br",
    phone: "(62) 98678-9123",
    company: "Martins Agro",
    jobTitle: "Proprietário",
    status: "contatado",
    ownerName: "Ana Souza",
    createdAt: "2026-07-14",
  },
  {
    id: "lead_11",
    name: "Vanessa Ribeiro",
    email: "vanessa@ribeiroeducacional.com.br",
    phone: "(51) 99789-1234",
    company: "Ribeiro Educacional",
    jobTitle: "Diretora Pedagógica",
    status: "desqualificado",
    ownerName: "Carlos Mendes",
    createdAt: "2026-05-30",
  },
  {
    id: "lead_12",
    name: "Gabriel Souza",
    email: "gabriel.souza@techflowbr.com",
    phone: "(11) 98890-1235",
    company: "TechFlow BR",
    jobTitle: "Head de Produto",
    status: "novo",
    ownerName: "Bruna Ferreira",
    createdAt: "2026-07-30",
  },
  {
    id: "lead_13",
    name: "Diego Martins",
    email: "diego.martins@martinscontabil.com.br",
    phone: "(31) 98234-1290",
    company: "Martins Contábil",
    jobTitle: "Sócio-Diretor",
    status: "qualificado",
    ownerName: "Bruna Ferreira",
    createdAt: "2026-07-05",
  },
  {
    id: "lead_14",
    name: "Beatriz Fontes",
    email: "beatriz.fontes@fontesarquitetura.com.br",
    phone: "(21) 99345-6721",
    company: "Fontes Arquitetura",
    jobTitle: "Diretora",
    status: "contatado",
    ownerName: "Ana Souza",
    createdAt: "2026-07-12",
  },
];

export const mockDeals: Deal[] = [
  {
    id: "deal_01",
    title: "Licenças CRM — Grupo Vialog",
    value: 18000,
    stage: "novo_lead",
    leadId: "lead_01",
    ownerName: "Ana Souza",
    dueDate: "2026-08-08",
  },
  {
    id: "deal_02",
    title: "Consultoria comercial — Almeida Advocacia",
    value: 6500,
    stage: "novo_lead",
    leadId: "lead_02",
    ownerName: "Carlos Mendes",
    dueDate: "2026-08-14",
  },
  {
    id: "deal_03",
    title: "Plano Pro anual — TechFlow BR",
    value: 24000,
    stage: "novo_lead",
    leadId: "lead_12",
    ownerName: "Bruna Ferreira",
    dueDate: "2026-08-02",
  },
  {
    id: "deal_04",
    title: "Implantação CRM — Nordeste Tech",
    value: 32000,
    stage: "contato_realizado",
    leadId: "lead_03",
    ownerName: "Bruna Ferreira",
    dueDate: "2026-08-05",
  },
  {
    id: "deal_05",
    title: "Upgrade de plano — Oliveira Logística",
    value: 9800,
    stage: "contato_realizado",
    leadId: "lead_06",
    ownerName: "Bruna Ferreira",
    dueDate: "2026-07-27",
  },
  {
    id: "deal_06",
    title: "Onboarding equipe comercial — Carvalho Consultoria",
    value: 5200,
    stage: "contato_realizado",
    leadId: "lead_08",
    ownerName: "Carlos Mendes",
    dueDate: "2026-08-10",
  },
  {
    id: "deal_07",
    title: "Proposta plano Pro — Bella Moda",
    value: 14500,
    stage: "proposta_enviada",
    leadId: "lead_05",
    ownerName: "Carlos Mendes",
    dueDate: "2026-08-01",
  },
  {
    id: "deal_08",
    title: "Expansão de licenças — EcoSolar Energia",
    value: 21000,
    stage: "proposta_enviada",
    leadId: "lead_09",
    ownerName: "Bruna Ferreira",
    dueDate: "2026-07-25",
  },
  {
    id: "deal_09",
    title: "Contrato anual — Clínica Vitta",
    value: 16800,
    stage: "negociacao",
    leadId: "lead_07",
    ownerName: "Ana Souza",
    dueDate: "2026-08-03",
  },
  {
    id: "deal_10",
    title: "Migração de planilhas — Martins Agro",
    value: 12300,
    stage: "negociacao",
    leadId: "lead_10",
    ownerName: "Ana Souza",
    dueDate: "2026-07-31",
  },
  {
    id: "deal_11",
    title: "Plano Pro 12 meses — Grupo Vialog",
    value: 27500,
    stage: "fechado_ganho",
    leadId: "lead_01",
    ownerName: "Ana Souza",
    dueDate: "2026-07-15",
  },
  {
    id: "deal_12",
    title: "Renovação anual — Bella Moda",
    value: 15000,
    stage: "fechado_ganho",
    leadId: "lead_05",
    ownerName: "Carlos Mendes",
    dueDate: "2026-07-08",
  },
  {
    id: "deal_13",
    title: "Plano Free → Pro — Ribeiro Educacional",
    value: 7200,
    stage: "fechado_perdido",
    leadId: "lead_11",
    ownerName: "Carlos Mendes",
    dueDate: "2026-06-28",
  },
  {
    id: "deal_14",
    title: "Licenças equipe — Santos Imóveis",
    value: 11400,
    stage: "fechado_perdido",
    leadId: "lead_04",
    ownerName: "Ana Souza",
    dueDate: "2026-06-20",
  },
  {
    id: "deal_15",
    title: "Proposta plano Pro — Martins Contábil",
    value: 9600,
    stage: "proposta_enviada",
    leadId: "lead_13",
    ownerName: "Bruna Ferreira",
    dueDate: "2026-08-07",
  },
  {
    id: "deal_16",
    title: "Contrato semestral — Fontes Arquitetura",
    value: 13400,
    stage: "negociacao",
    leadId: "lead_14",
    ownerName: "Ana Souza",
    dueDate: "2026-08-02",
  },
  {
    id: "deal_17",
    title: "Upgrade de licenças — Nordeste Tech",
    value: 19800,
    stage: "fechado_ganho",
    leadId: "lead_03",
    ownerName: "Bruna Ferreira",
    dueDate: "2026-07-10",
  },
  {
    id: "deal_18",
    title: "Plano Pro anual — EcoSolar Energia",
    value: 15600,
    stage: "fechado_perdido",
    leadId: "lead_09",
    ownerName: "Bruna Ferreira",
    dueDate: "2026-07-05",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "act_01",
    leadId: "lead_01",
    type: "email",
    author: "Ana Souza",
    description: "Enviado e-mail de apresentação com o catálogo de planos.",
    date: "2026-06-03",
  },
  {
    id: "act_02",
    leadId: "lead_01",
    type: "ligacao",
    author: "Ana Souza",
    description: "Ligação de descoberta. Mariana confirmou orçamento aprovado para o trimestre.",
    date: "2026-06-10",
  },
  {
    id: "act_03",
    leadId: "lead_01",
    type: "reuniao",
    author: "Ana Souza",
    description: "Reunião de demonstração do produto com a equipe de compras.",
    date: "2026-06-20",
  },
  {
    id: "act_04",
    leadId: "lead_01",
    type: "nota",
    author: "Ana Souza",
    description: "Lead qualificado — avançar proposta comercial na próxima semana.",
    date: "2026-07-05",
  },
  {
    id: "act_05",
    leadId: "lead_03",
    type: "email",
    author: "Bruna Ferreira",
    description: "Enviado e-mail com respostas técnicas sobre integração via API.",
    date: "2026-07-19",
  },
  {
    id: "act_06",
    leadId: "lead_03",
    type: "ligacao",
    author: "Bruna Ferreira",
    description: "Ligação de alinhamento com o time técnico da Nordeste Tech.",
    date: "2026-07-22",
  },
  {
    id: "act_07",
    leadId: "lead_05",
    type: "email",
    author: "Carlos Mendes",
    description: "Primeiro contato por e-mail após indicação de cliente atual.",
    date: "2026-06-26",
  },
  {
    id: "act_08",
    leadId: "lead_05",
    type: "reuniao",
    author: "Carlos Mendes",
    description: "Reunião de apresentação do produto via videochamada.",
    date: "2026-07-02",
  },
  {
    id: "act_09",
    leadId: "lead_05",
    type: "nota",
    author: "Carlos Mendes",
    description: "Camila pediu proposta com desconto para pagamento anual.",
    date: "2026-07-15",
  },
  {
    id: "act_10",
    leadId: "lead_07",
    type: "ligacao",
    author: "Ana Souza",
    description: "Ligação inicial. Fernanda demonstrou interesse em automatizar o funil de vendas.",
    date: "2026-07-11",
  },
  {
    id: "act_11",
    leadId: "lead_07",
    type: "email",
    author: "Ana Souza",
    description: "Envio de material comparativo entre planos Free e Pro.",
    date: "2026-07-16",
  },
  {
    id: "act_12",
    leadId: "lead_10",
    type: "email",
    author: "Ana Souza",
    description: "E-mail de apresentação enviado após contato via formulário do site.",
    date: "2026-07-15",
  },
  {
    id: "act_13",
    leadId: "lead_10",
    type: "ligacao",
    author: "Ana Souza",
    description: "Ligação de qualificação. Lucas busca substituir controle em planilhas.",
    date: "2026-07-20",
  },
  {
    id: "act_14",
    leadId: "lead_10",
    type: "reuniao",
    author: "Ana Souza",
    description: "Reunião de demonstração agendada com o time da fazenda.",
    date: "2026-07-25",
  },
];
